### ISSUE TITLE
YAML rules applied on each title

### ISSUE THREAD

**Issue by DTasev** [DTasev/WindowTracker#1]
Different processes use different windows title conventions, for example:
- chrome: <tab name> - Google Chrome
- cmd: only has the full path to the executable
- git-bash: MNIGW(64/32):<current directory>

As there isn't a single way to process all of these, a config file should be added, to allow the addition of custom rules for an executable. It should follow YAML format, in order to be easily readable. A sample rule for chrome might be:

```yaml
chrome: # the name of the executable, .exe is omitted
  reverse: true # start looking from the end
  separator: '-' # character to split the string, then we have a list with the name of the tab, and the name of the process
  masterName: 1 # index of the name of the process
  subName: 0 # index of the name of the tabs
  name: Potatoes # custom name that will be used for this process
# alternative
  regex: ....
```
Regex could also be supported, and use the regex implementation of C# (with which I am not familiar).
This is just an example and will change.
